load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

LIB_DEPS = [
    "@maven//:org_slf4j_slf4j_api",
    "@maven//:org_projectlombok_lombok",
]

java_library(
    name = "lib",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"], allow_empty = True),
    plugins = ["//build-support/bazel:lombok"],
    deps = LIB_DEPS,
)
