#!/bin/sh
# bb_runner invokes this only at idle/action boundaries, with one slot per pod.
# This daemon belongs solely to this worker; no host Docker socket is mounted.
set -eu
export DOCKER_HOST=tcp://127.0.0.1:2375
containers=$(docker ps -aq)
if [ -n "$containers" ]; then
  # IDs are generated by Docker, not user-provided shell text.
  docker rm --force --volumes $containers
fi
docker system prune --force
# Default to 20 GiB on 40-GiB scratch volumes. Larger-volume experiments may
# increase the threshold while reserving space for builds and running containers.
cache_limit=${DOCKER_IMAGE_CACHE_MAX_BYTES:-21474836480}
image_bytes=$(python3 - <<'PY'
import json, urllib.request
with urllib.request.urlopen('http://127.0.0.1:2375/system/df', timeout=120) as response:
    usage = json.load(response)
size = usage.get('LayersSize', 0)
print(size)
PY
)
printf 'Retained Docker image bytes: %s\n' "$image_bytes"
if [ "$image_bytes" -gt "$cache_limit" ]; then
  docker image prune --all --force
fi
