#!/bin/sh
# bb_runner invokes this only at idle/action boundaries, with one slot per pod.
# This daemon belongs solely to this worker; no host Docker socket is mounted.
set -eu
export DOCKER_HOST=tcp://127.0.0.1:2375
containers=$(docker ps -aq)
if [ -n "$containers" ]; then
  # IDs are generated by Docker, not user-provided shell text.
  docker rm --force --volumes $containers
fi
docker system prune --force
# Preserve reusable tagged images until their layers exceed 20 GiB. Leave room
# below the 40-GiB scratch-volume ceiling for pulls, builds, and a running test's data.
image_bytes=$(python3 - <<'PY'
import json, urllib.request
with urllib.request.urlopen('http://127.0.0.1:2375/system/df', timeout=120) as response:
    usage = json.load(response)
size = usage.get('LayersSize', 0)
print(size)
PY
)
printf 'Retained Docker image bytes: %s\n' "$image_bytes"
if [ "$image_bytes" -gt 21474836480 ]; then
  docker image prune --all --force
fi
