load("@rules_java//java:defs.bzl", "java_plugin")

package(default_visibility = ["//visibility:public"])

exports_files(["pytest_main.py", "requirements_lock.txt", "console_requirements_lock.txt", "maven_install.json"])

java_plugin(
    name = "lombok",
    generates_api = True,
    processor_class = "lombok.launch.AnnotationProcessorHider$AnnotationProcessor",
    deps = ["@maven//:org_projectlombok_lombok"],
)
