apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: migrations-buildbarn
configMapGenerator:
- name: buildbarn-fixture-storage
  files:
  - common.libsonnet
  - storage.jsonnet
generatorOptions:
  disableNameSuffixHash: true
