apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: migrations-buildbarn
resources:
- ../buildbarn/image-cache
configMapGenerator:
- name: buildbarn-image-cache
  behavior: replace
  files:
  - config.yml
patches:
- target:
    kind: NetworkPolicy
    name: buildbarn-image-cache-downloads
  patch: |-
    - op: replace
      path: /spec/egress
      value: []
