# Adapted from buildbarn/bb-deployments d4a6ca38e5f77959b42fccaa34a3320253683bc2.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: migrations-buildbarn
resources:
- namespace.yaml
- network-policy.yaml
- frontend.yaml
- scheduler.yaml
- storage.yaml
- worker-ubuntu22-04.yaml
configMapGenerator:
- name: buildbarn-config
  files:
  - config/common.libsonnet
  - config/frontend.jsonnet
  - config/runner-ubuntu22-04.jsonnet
  - config/scheduler.jsonnet
  - config/storage.jsonnet
  - config/worker-ubuntu22-04.jsonnet
