apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: migrations-buildbarn
resources:
- namespace.yaml
- worker-storage-class.yaml
- network-policy.yaml
- frontend.yaml
- scheduler.yaml
- storage.yaml
- worker-ubuntu22-04.yaml
- worker-integration.yaml
- integration-network-policy.yaml
- autoscaler.yaml
- worker-integration-large.yaml
configMapGenerator:
- name: buildbarn-config
  files:
  - config/common.libsonnet
  - config/frontend.jsonnet
  - config/runner-ubuntu22-04.jsonnet
  - config/scheduler.jsonnet
  - config/storage.jsonnet
  - config/worker-ubuntu22-04.jsonnet
- name: buildbarn-integration-config
  files:
  - config/common.libsonnet
  - config/runner-ubuntu22-04.jsonnet
  - config/worker-integration.jsonnet
  - config/start-docker.sh
  - config/runner-integration.jsonnet
  - config/clean-docker.sh
- name: buildbarn-prometheus-config
  files:
  - config/prometheus.yaml
  - config/autoscaler-rules.yaml
  - config/autoscaler-rules.test.yaml
- name: buildbarn-autoscaler-config
  files:
  - config/autoscaler.jsonnet
- name: buildbarn-integration-large-config
  files:
  - config/common.libsonnet
  - config/runner-ubuntu22-04.jsonnet
  - config/worker-integration-large.jsonnet
  - config/start-docker.sh
  - config/runner-integration.jsonnet
  - config/clean-docker.sh
